Antimonov HomeWork10 done
eugene-okulik/QAP-13onl pull request #130
Opened 2023-05-12 15:41 UTC by slnjke

2023-05-14 06:33 UTC, eugene-okulik requested changes
Всё хорошо. Вся часть про классы сделана отлично.  
Но нашелся баг, который нужно пофиксить.

2023-05-14 06:33 UTC, eugene-okulik commented on homework/danil_antimonov/homeWork_10/homeWork_10.py
> +        self.spike = spike
круто, что внедрил еще и индивидуальные характеристики.

2023-05-14 06:33 UTC, eugene-okulik commented on homework/danil_antimonov/homeWork_10/homeWork_10.py
> +    def __repr__(self):
:+1:

2023-05-14 06:33 UTC, eugene-okulik commented on homework/danil_antimonov/homeWork_10/homeWork_10.py
> +        lifetime_bouquet = sum(list(map(lambda flower: flower.lifetime, self.list_of_flowers))) / 2
а почему у тебя здесь деление на 2? Видимо, когда ты создавал этот метод, у тебя в букете было всего 2 цветка. Но, по итогу, сейчас создается букет из трех цветков и эта формула работает неправильно. Хорошо бы сделать так, чтобы код сам понимал сколько там цветов в букете и делил на это число.

2023-05-16 15:18 UTC, slnjke commented on homework/danil_antimonov/homeWork_10/homeWork_10.py
> +        lifetime_bouquet = sum(list(map(lambda flower: flower.lifetime, self.list_of_flowers))) / 2
Исправил

2023-05-17 06:11 UTC, eugene-okulik approved these changes

2023-05-17 06:11 UTC, merged