alina egorova: homework_7 completed
eugene-okulik/QAP-13onl pull request #145
Opened 2023-05-26 12:55 UTC by Alekkro

2023-05-27 09:07 UTC, eugene-okulik requested changes
Всё что в комментах можно не исправлять, но точно стоит себе учесть на будущее.  
А вот что точно нужно исправить, так это расположение папки homework_7 - она сейчас не внутри твоей папки, а внутри папки homework

2023-05-27 09:07 UTC, eugene-okulik commented on homework/homework_7/7.2.py
> +    nums.append(int(i))
вот это можно было сделать с помощью list comprehension:
```python
nums = [int(x) for x in num]
```

2023-05-27 09:07 UTC, eugene-okulik commented on homework/homework_7/7.2.py
> +for i in num:
Название переменной `i` очень сбивает с толку. Обычно таким названием называют переменную-счетчик. Ну типа в ситуациях  
```python
for i in range(10)
```
Здесь же у тебя хранится очередное число из чисел введенных пользователем. Круто бы назвать его `num`, но это у тебя уже занято. Поэтому список пользовательский я бы назвал `numbers`, а переменную `nums` вообще бы не создавал, а сделал бы
```python
numbers = [int(num) for num in numbers]
```

2023-06-01 01:59 UTC, Alekkro commented
> Всё, что в комментах можно не исправлять, но точно стоит себе учесть на будущее. А вот что точно нужно исправить, так это расположение папки homework_7 - она ​​сейчас не внутри вашей папки, а внутри папки homework

как изменить расположение папки homework_7? У меня снова попортились отношения с github :(

2023-06-01 06:17 UTC, eugene-okulik commented
> > Всё, что в комментах можно не исправлять, но точно стоит себе учесть на будущее. А вот что точно нужно исправить, так это расположение папки homework_7 - она ​​сейчас не внутри вашей папки, а внутри папки homework
> 
> как изменить расположение папки homework_7? У меня снова попортились отношения с github :(

Все очень просто. Заходишь в пайчарме в свою ветку `alina_egorova_homework_7`, двигаешь мышкой папочки куда нужно -> делаешь коммит -> делаешь пуш. Пиши в телегу если будут проблемы.

2023-06-07 06:20 UTC, eugene-okulik approved these changes

2023-06-07 06:20 UTC, merged