added solutions for the homework 4
eugene-okulik/QAP-13onl pull request #40
Opened 2023-04-06 13:12 UTC by VladZera

2023-04-08 09:24 UTC, eugene-okulik commented
Не заглядывая в код - первое замечание: название пул реквеста не соответствует требованиям  
https://github.com/eugene-okulik/QAP-13onl/wiki/%D0%98%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B1%D1%80%D0%B0%D0%BD%D1%87%D0%B5%D0%B9,-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D0%BE%D0%B2,-%D0%BF%D1%83%D0%BB%D0%BB-%D1%80%D0%B5%D0%BA%D0%B2%D0%B5%D1%81%D1%82%D0%BE%D0%B2#pull-requests

2023-04-08 09:26 UTC, eugene-okulik requested changes
В целом неплохо, но тест на внимательность не пройден ))

2023-04-08 09:26 UTC, eugene-okulik commented on homework/vlad_zavistovich/homework_4/task_1.py
> +my_dict['dict']['i am a tuple'] = 'hello friend'  # Added new element with key 'i am a tuple'.
В задании было добавить ключ не `'i am a tuple'`, а ключ `('i am a tuple',)` - кортеж с одним элементом

2023-04-11 15:35 UTC, VladZera commented on homework/vlad_zavistovich/homework_4/task_1.py
> +my_dict['dict']['i am a tuple'] = 'hello friend'  # Added new element with key 'i am a tuple'.
Исправил)

2023-04-12 05:55 UTC, eugene-okulik approved these changes

2023-04-12 05:56 UTC, merged