Danil_homework_4_done
eugene-okulik/QAP-13onl pull request #55
Opened 2023-04-10 17:41 UTC by slnjke

2023-04-12 06:23 UTC, eugene-okulik requested changes
В целом все хорошо, но пара тестов на внимательность провалены ))

2023-04-12 06:23 UTC, eugene-okulik commented on homework/danil_antimonov/homeWork_4/homework_4_1.py
> +           'set': {'text1', 'text2', 1, 3, 6, 7, 'text', False, 12.3}, 'str': 'Wery_long_string'}
у элемента `str` не то содержимое, что в задании

2023-04-14 13:08 UTC, slnjke commented on homework/danil_antimonov/homeWork_4/homework_4_1.py
> +           'set': {'text1', 'text2', 1, 3, 6, 7, 'text', False, 12.3}, 'str': 'Wery_long_string'}
fixed

2023-04-18 05:28 UTC, eugene-okulik approved these changes

2023-04-18 05:28 UTC, merged