kiryl berazhny: homework 5 completed
eugene-okulik/QAP-13onl pull request #56
Opened 2023-04-10 21:25 UTC by kirylberag

2023-04-18 05:53 UTC, eugene-okulik requested changes
Все хорошо. Но исправь то, что в комменте. Такие вещи, хоть и не ломают программу, но считаются большой ошибкой.

2023-04-18 05:53 UTC, eugene-okulik commented on homework/kiryl_berazhny/kiryl_berazhny_homework5/Task_3.py
> +print(sum(my_list) / 15)
Вот здесь 15 - это магическое число. Т.е. непонятно почему 15 и откуда оно берется. Теоретически, когда тебя попросят сделать то же самое, но для 20 чисел, есть вероятность, что ты поменяешь 15 на 20 в `range` и забудешь поменять здесь. Поэтому правильнее делать так, чтобы или код сам вычислял сколько там элементов `len(my_list)` или чтобы это 15 хранилось в переменной и тогда в обоих местах пользоваться переменной.  
Про магические числа: https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5) - раздел "Плохая практика программирования"

2023-04-18 06:32 UTC, eugene-okulik commented on homework/kiryl_berazhny/kiryl_berazhny_homework5/Task_3.py
> +print(sum(my_list) / 15)
Но здесь в конце у тебя всё еще остается 15

2023-04-18 07:45 UTC, kirylberag commented on homework/kiryl_berazhny/kiryl_berazhny_homework5/Task_3.py
> +print(sum(my_list) / 15)
Готово, исправил. Спасибо, что с пояснениями замечание, все логично.

2023-04-21 12:52 UTC, eugene-okulik approved these changes

2023-04-21 12:53 UTC, merged