question about task_1
eugene-okulik/QAP-13onl pull request #72
Opened 2023-04-14 22:14 UTC by PavelLaushuk

2023-04-19 21:31 UTC, PavelLaushuk commented
Изменил название главное папки была ошибка , pavel_laushuk - pavel_lavshuk.

2023-04-26 05:48 UTC, eugene-okulik requested changes
Судя по тому, что у тебя залетело в поул реквест, ты создал новую ветку не из свежего `main`, а из чего-то другого.  
Название пул реквеста должно соответствовать требованиям: https://github.com/eugene-okulik/QAP-13onl/wiki/%D0%98%D0%BC%D0%B5%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B1%D1%80%D0%B0%D0%BD%D1%87%D0%B5%D0%B9,-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B8%D1%82%D0%BE%D0%B2,-%D0%BF%D1%83%D0%BB%D0%BB-%D1%80%D0%B5%D0%BA%D0%B2%D0%B5%D1%81%D1%82%D0%BE%D0%B2#pull-requests  
Нужно исправить последнее задание. Такие вещи, хоть и не ломают программу, но считаются большой ошибкой.

2023-04-26 05:48 UTC, eugene-okulik commented on homework/pavel_lavshuk/homework_5/task_3.py
> +print(max(a), min(a), sum(a), sum(a) / 15)
Вот здесь 15 - это магическое число. Т.е. непонятно почему 15 и откуда оно берется. Теоретически, когда тебя попросят сделать то же самое, но для 20 чисел, есть вероятность, что ты поменяешь 15 на 20 в `range` и забудешь поменять здесь. Поэтому правильнее делать так, чтобы или код сам вычислял сколько там элементов `len(my_list)` или чтобы это 15 хранилось в переменной и тогда в обоих местах пользоваться переменной.  
Про магические числа: https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5) - раздел "Плохая практика программирования"

2023-04-26 05:48 UTC, eugene-okulik commented on homework/pavel_lavshuk/homework_5/task_2.py
> +    b = float(input())
Было бы неплохо написать пользователю, что здесь от него ждут число

2023-05-05 05:14 UTC, eugene-okulik approved these changes

2023-05-05 05:14 UTC, merged